// This file is generated by rust-protobuf 3.1.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proto/registry/v1/account.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

///  CreateAccount Request contains the three keys needed to create an account on Sonr
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:sonrio.motor.registry.v1.CreateAccountRequest)
pub struct CreateAccountRequest {
    // message fields
    // @@protoc_insertion_point(field:sonrio.motor.registry.v1.CreateAccountRequest.password)
    pub password: ::std::string::String,
    // @@protoc_insertion_point(field:sonrio.motor.registry.v1.CreateAccountRequest.aes_dsc_key)
    pub aes_dsc_key: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:sonrio.motor.registry.v1.CreateAccountRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CreateAccountRequest {
    fn default() -> &'a CreateAccountRequest {
        <CreateAccountRequest as ::protobuf::Message>::default_instance()
    }
}

impl CreateAccountRequest {
    pub fn new() -> CreateAccountRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "password",
            |m: &CreateAccountRequest| { &m.password },
            |m: &mut CreateAccountRequest| { &mut m.password },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "aes_dsc_key",
            |m: &CreateAccountRequest| { &m.aes_dsc_key },
            |m: &mut CreateAccountRequest| { &mut m.aes_dsc_key },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CreateAccountRequest>(
            "CreateAccountRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CreateAccountRequest {
    const NAME: &'static str = "CreateAccountRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.password = is.read_string()?;
                },
                18 => {
                    self.aes_dsc_key = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.password.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.password);
        }
        if !self.aes_dsc_key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.aes_dsc_key);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.password.is_empty() {
            os.write_string(1, &self.password)?;
        }
        if !self.aes_dsc_key.is_empty() {
            os.write_bytes(2, &self.aes_dsc_key)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CreateAccountRequest {
        CreateAccountRequest::new()
    }

    fn clear(&mut self) {
        self.password.clear();
        self.aes_dsc_key.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CreateAccountRequest {
        static instance: CreateAccountRequest = CreateAccountRequest {
            password: ::std::string::String::new(),
            aes_dsc_key: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CreateAccountRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CreateAccountRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CreateAccountRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreateAccountRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:sonrio.motor.registry.v1.CreateAccountResponse)
pub struct CreateAccountResponse {
    // message fields
    // @@protoc_insertion_point(field:sonrio.motor.registry.v1.CreateAccountResponse.aes_psk)
    pub aes_psk: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:sonrio.motor.registry.v1.CreateAccountResponse.address)
    pub address: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:sonrio.motor.registry.v1.CreateAccountResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CreateAccountResponse {
    fn default() -> &'a CreateAccountResponse {
        <CreateAccountResponse as ::protobuf::Message>::default_instance()
    }
}

impl CreateAccountResponse {
    pub fn new() -> CreateAccountResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "aes_psk",
            |m: &CreateAccountResponse| { &m.aes_psk },
            |m: &mut CreateAccountResponse| { &mut m.aes_psk },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "address",
            |m: &CreateAccountResponse| { &m.address },
            |m: &mut CreateAccountResponse| { &mut m.address },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CreateAccountResponse>(
            "CreateAccountResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CreateAccountResponse {
    const NAME: &'static str = "CreateAccountResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.aes_psk = is.read_bytes()?;
                },
                18 => {
                    self.address = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.aes_psk.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.aes_psk);
        }
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.address);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.aes_psk.is_empty() {
            os.write_bytes(1, &self.aes_psk)?;
        }
        if !self.address.is_empty() {
            os.write_string(2, &self.address)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CreateAccountResponse {
        CreateAccountResponse::new()
    }

    fn clear(&mut self) {
        self.aes_psk.clear();
        self.address.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CreateAccountResponse {
        static instance: CreateAccountResponse = CreateAccountResponse {
            aes_psk: ::std::vec::Vec::new(),
            address: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CreateAccountResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CreateAccountResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CreateAccountResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreateAccountResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1fproto/registry/v1/account.proto\x12\x18sonrio.motor.registry.v1\"R\
    \n\x14CreateAccountRequest\x12\x1a\n\x08password\x18\x01\x20\x01(\tR\x08\
    password\x12\x1e\n\x0baes_dsc_key\x18\x02\x20\x01(\x0cR\taesDscKey\"J\n\
    \x15CreateAccountResponse\x12\x17\n\x07aes_psk\x18\x01\x20\x01(\x0cR\x06\
    aesPsk\x12\x18\n\x07address\x18\x02\x20\x01(\tR\x07addressB.Z,github.com\
    /sonr-io/sonr/motor/types/registryJ\x92\x03\n\x06\x12\x04\0\0\x0e\x01\n\
    \x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0!\n\x08\n\
    \x01\x08\x12\x03\x03\0C\n\t\n\x02\x08\x0b\x12\x03\x03\0C\n_\n\x02\x04\0\
    \x12\x04\x06\0\t\x01\x1aS\x20CreateAccount\x20Request\x20contains\x20the\
    \x20three\x20keys\x20needed\x20to\x20create\x20an\x20account\x20on\x20So\
    nr\n\n\n\n\x03\x04\0\x01\x12\x03\x06\x08\x1c\n\x0b\n\x04\x04\0\x02\0\x12\
    \x03\x07\x02\x16\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x07\x02\x08\n\x0c\n\
    \x05\x04\0\x02\0\x01\x12\x03\x07\t\x11\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03\x07\x14\x15\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x08\x02\x18\n\x0c\n\
    \x05\x04\0\x02\x01\x05\x12\x03\x08\x02\x07\n\x0c\n\x05\x04\0\x02\x01\x01\
    \x12\x03\x08\x08\x13\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x08\x16\x17\n\
    \n\n\x02\x04\x01\x12\x04\x0b\0\x0e\x01\n\n\n\x03\x04\x01\x01\x12\x03\x0b\
    \x08\x1d\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x0c\x02\x14\n\x0c\n\x05\x04\
    \x01\x02\0\x05\x12\x03\x0c\x02\x07\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\
    \x0c\x08\x0f\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x0c\x12\x13\n\x0b\n\
    \x04\x04\x01\x02\x01\x12\x03\r\x02\x15\n\x0c\n\x05\x04\x01\x02\x01\x05\
    \x12\x03\r\x02\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\r\t\x10\n\x0c\
    \n\x05\x04\x01\x02\x01\x03\x12\x03\r\x13\x14b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(CreateAccountRequest::generated_message_descriptor_data());
            messages.push(CreateAccountResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
